/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebastian
 */
package view;

import entity.BankAccount;
import entity.User;
import service.AdminService;
import service.UserService;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class adminView extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorFrame
     */
    private UserService us = new UserService();
    private AdminService as = new AdminService();
    public adminView() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        StartPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        addUserPanel = new javax.swing.JPanel();
        firstNameAddLabel = new javax.swing.JLabel();
        lastNameAddLabel = new javax.swing.JLabel();
        cnpAddLabel = new javax.swing.JLabel();
        birthdateAddLabel = new javax.swing.JLabel();
        emailAddLabel = new javax.swing.JLabel();
        firstNameAddText = new javax.swing.JTextField();
        lastNameAddText = new javax.swing.JTextField();
        phoneAddLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        countryText = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        streetText = new javax.swing.JTextField();
        numberText = new javax.swing.JTextField();
        cnpAddText = new javax.swing.JTextField();
        birthdateAddText = new javax.swing.JTextField();
        emailAddText = new javax.swing.JTextField();
        phoneAddText = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        addUserButton = new javax.swing.JButton();
        ConfirmUser = new javax.swing.JButton();
        deleteUserPanel = new javax.swing.JPanel();
        userDeleteLabel = new javax.swing.JLabel();
        userDeleteCombo = new javax.swing.JComboBox<>();
        userDeleteButton = new javax.swing.JButton();
        createAccountPanel = new javax.swing.JPanel();
        userCreateAccountLabel = new javax.swing.JLabel();
        userCreateAccountText = new javax.swing.JComboBox<>();
        accountTypeLabel = new javax.swing.JLabel();
        accountTypeText = new javax.swing.JComboBox<>();
        balanceLabel = new javax.swing.JLabel();
        balanceText = new javax.swing.JTextField();
        addAccountButton = new javax.swing.JButton();
        deleteAccount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        createCredit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel3.setText("Country");

        jLabel11.setText("Number");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNameAddLabel.setText("First Name:");

        lastNameAddLabel.setText("Last Name:");

        cnpAddLabel.setText("CNP:");

        birthdateAddLabel.setText("Birthdate:");

        emailAddLabel.setText("Email:");

        phoneAddLabel.setText("Phone:");

        addressLabel.setText("Address:");

        countryLabel.setText("Country");

        streetLabel.setText("Street");

        countryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextActionPerformed(evt);
            }
        });

        cityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextActionPerformed(evt);
            }
        });

        birthdateAddText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateAddTextActionPerformed(evt);
            }
        });




//////////////////////////////////////////////////////////////////////////////////////////////////
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }

            private void jComboBoxActionPerformed(ActionEvent evt) {
                String aux;
                aux = (String) jComboBox1.getSelectedItem();
                CreateComboBox2(aux);

            }
        });

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }

            private void jComboBox3ActionPerformed(ActionEvent evt) {
                String aux;
                aux = (String) jComboBox3.getSelectedItem();
                CreateComboBox4(aux);

            }
        });

///////////////////////////////////////////////////////////////////////////////////////////////////



        cityLabel.setText("City");

        numberLabel.setText("Nr");

        addUserButton.setText("Add user");

        javax.swing.GroupLayout addUserPanelLayout = new javax.swing.GroupLayout(addUserPanel);
        addUserPanel.setLayout(addUserPanelLayout);
        addUserPanelLayout.setHorizontalGroup(
                addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addUserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(addUserPanelLayout.createSequentialGroup()
                                                        .addComponent(birthdateAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(birthdateAddText))
                                                .addGroup(addUserPanelLayout.createSequentialGroup()
                                                        .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(cnpAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(lastNameAddLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(firstNameAddLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(cnpAddText, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(firstNameAddText)
                                                                        .addComponent(lastNameAddText, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))))
                                        .addGroup(addUserPanelLayout.createSequentialGroup()
                                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(emailAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(phoneAddLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(emailAddText)
                                                        .addComponent(phoneAddText, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                                        .addGroup(addUserPanelLayout.createSequentialGroup()
                                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                        .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(countryText)
                                                                .addComponent(countryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(addUserPanelLayout.createSequentialGroup()
                                                                .addComponent(streetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(addUserPanelLayout.createSequentialGroup()
                                                                .addComponent(streetText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(75, Short.MAX_VALUE))
        );
        addUserPanelLayout.setVerticalGroup(
                addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addUserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstNameAddText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstNameAddLabel))
                                .addGap(11, 11, 11)
                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastNameAddLabel)
                                        .addComponent(lastNameAddText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cnpAddLabel)
                                        .addComponent(cnpAddText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(birthdateAddLabel)
                                        .addComponent(birthdateAddText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailAddText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(phoneAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phoneAddText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(countryLabel)
                                        .addComponent(cityLabel)
                                        .addComponent(streetLabel)
                                        .addComponent(numberLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(countryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(streetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(addUserButton)
                                .addGap(19, 19, 19))
        );

        tabbedPane.addTab("Add User", addUserPanel);

        userDeleteLabel.setText("Select user:");

        //userDeleteCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        createUserDeleteComboBox();
        userDeleteButton.setText("Delete");

        javax.swing.GroupLayout deleteUserPanelLayout = new javax.swing.GroupLayout(deleteUserPanel);
        deleteUserPanel.setLayout(deleteUserPanelLayout);
        deleteUserPanelLayout.setHorizontalGroup(
                deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteUserPanelLayout.createSequentialGroup()
                                .addContainerGap(19, Short.MAX_VALUE)
                                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(userDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(deleteUserPanelLayout.createSequentialGroup()
                                                .addComponent(userDeleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(userDeleteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(183, 183, 183))
        );
        deleteUserPanelLayout.setVerticalGroup(
                deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deleteUserPanelLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userDeleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userDeleteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(userDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(137, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Delete User", deleteUserPanel);

        userCreateAccountLabel.setText("Select user:");

        //userCreateAccountText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userCreateAccountComboBox();
        accountTypeLabel.setText("Account type:");

        accountTypeText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cont de debit in lei",
                "cont de debit in euro", "cont credit in lei", "cont de credit in euro" }));

        balanceLabel.setText("Balance:");

        addAccountButton.setText("Add account");

        javax.swing.GroupLayout createAccountPanelLayout = new javax.swing.GroupLayout(createAccountPanel);
        createAccountPanel.setLayout(createAccountPanelLayout);
        createAccountPanelLayout.setHorizontalGroup(
                createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createAccountPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(accountTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(userCreateAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userCreateAccountText, 0, 175, Short.MAX_VALUE)
                                        .addComponent(accountTypeText, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(balanceText))
                                .addContainerGap(130, Short.MAX_VALUE))
        );
        createAccountPanelLayout.setVerticalGroup(
                createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createAccountPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userCreateAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(userCreateAccountText, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(accountTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(accountTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(addAccountButton)
                                .addContainerGap(95, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Create account", createAccountPanel);

        jLabel1.setText("Select user:");

        //jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CreateComboBox1();

        jLabel2.setText("Select account:");

        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
       // CreateComboBox2();
       // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        jButton1.setText("delete account");
        //ConfirmUser.setText("confirm user");
        javax.swing.GroupLayout deleteAccountLayout = new javax.swing.GroupLayout(deleteAccount);
        deleteAccount.setLayout(deleteAccountLayout);
        deleteAccountLayout.setHorizontalGroup(
                deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deleteAccountLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        //.addComponent(ConfirmUser) //AICI
                                        .addGroup(deleteAccountLayout.createSequentialGroup()
                                                .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(143, Short.MAX_VALUE))
        );
        deleteAccountLayout.setVerticalGroup(
                deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deleteAccountLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(deleteAccountLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(deleteAccountLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33)
                                .addComponent(jButton1)
                                .addContainerGap(140, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Delete account", deleteAccount);

        jLabel4.setText("Select user:");

        jLabel5.setText("Select bank account:");

        jLabel6.setText("Interest rate:");

        jLabel7.setText("Credited Amount :");

        jLabel8.setText("End date:");

        jLabel9.setText("User guarantee:");

        //jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CreateComboBox3();

        //jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Job");

        jLabel12.setText("Salary/month");

        jLabel13.setText("Wealth");

        jButton2.setText("Create credit");

        javax.swing.GroupLayout createCreditLayout = new javax.swing.GroupLayout(createCredit);
        createCredit.setLayout(createCreditLayout);
        createCreditLayout.setHorizontalGroup(
                createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createCreditLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2)
                                        .addGroup(createCreditLayout.createSequentialGroup()
                                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jComboBox3, 0, 172, Short.MAX_VALUE)
                                                                        .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jTextField1)
                                                                        .addComponent(jTextField2)
                                                                        .addComponent(jTextField3))
                                                                .addGroup(createCreditLayout.createSequentialGroup()
                                                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                                                                .addComponent(jTextField5)))))
                                                .addGap(18, 18, 18)
                                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(37, Short.MAX_VALUE))
        );
        createCreditLayout.setVerticalGroup(
                createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createCreditLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(createCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(25, 25, 25))
        );

        tabbedPane.addTab("Create credit", createCredit);

        javax.swing.GroupLayout StartPanelLayout = new javax.swing.GroupLayout(StartPanel);
        StartPanel.setLayout(StartPanelLayout);
        StartPanelLayout.setHorizontalGroup(
                StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabbedPane)
        );
        StartPanelLayout.setVerticalGroup(
                StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void countryTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cityTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void birthdateAddTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }



    // Variables declaration - do not modify
    private javax.swing.JPanel StartPanel;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JComboBox<String> accountTypeText;
    private javax.swing.JButton addAccountButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JPanel addUserPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JTextField balanceText;
    private javax.swing.JLabel birthdateAddLabel;
    private javax.swing.JTextField birthdateAddText;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityText;
    private javax.swing.JLabel cnpAddLabel;
    private javax.swing.JTextField cnpAddText;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryText;
    private javax.swing.JPanel createAccountPanel;
    private javax.swing.JPanel createCredit;
    private javax.swing.JPanel deleteAccount;
    private javax.swing.JPanel deleteUserPanel;
    private javax.swing.JLabel emailAddLabel;
    private javax.swing.JTextField emailAddText;
    private javax.swing.JLabel firstNameAddLabel;
    private javax.swing.JTextField firstNameAddText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton ConfirmUser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lastNameAddLabel;
    private javax.swing.JTextField lastNameAddText;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numberText;
    private javax.swing.JLabel phoneAddLabel;
    private javax.swing.JTextField phoneAddText;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetText;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel userCreateAccountLabel;
    private javax.swing.JComboBox<String> userCreateAccountText;
    private javax.swing.JButton userDeleteButton;
    private javax.swing.JComboBox<String> userDeleteCombo;
    private javax.swing.JLabel userDeleteLabel;
    // End of variables declaration

    public double getInterestRate (){
        String s = jTextField1.getText();
        double q = Double.parseDouble(s);
        return q;
    }
    public double getCreditAmount (){
        String s = jTextField2.getText();
        double q = Double.parseDouble(s);
        return q;
    }

    public String getEndDate (){
        String s = jTextField3.getText();
        return s;
    }
    public String getJob (){
        String s = jTextField4.getText();
        return s;
    }
    public double getSalary (){
        String s = jTextField5.getText();
        double q = Double.parseDouble(s);
        return q;
    }
    public double getWealth (){
        String s = jTextField6.getText();
        double q = Double.parseDouble(s);
        return q;
    }

    public String getFirstNameAddText (){
        String s = firstNameAddText.getText();
        return s;
    }
    public String getLastNameAddText (){
        String s = lastNameAddText.getText();
        return s;
    }
    public String getCnpAddText (){
        String s = cnpAddText.getText();
        return s;
    }
    public String getEmailAddText (){
        String s = emailAddText.getText();
        return s;
    }
    public String getBirthdateAddText (){
        String s = birthdateAddText.getText();
        return s;
    }
    public String getPhoneAddText (){
        String s = phoneAddText.getText();
        return s;
    }
    public String getCountryAddText (){
        String s = countryText.getText();
        return s;
    }
    public String getStreetAddText (){
        String s = streetText.getText();
        return s;
    }
    public int getNumberAddText (){
        String s = numberText.getText();
        int n = Integer.parseInt(s);
        return n;
    }
    public String getCityAddText (){
        String s = cityText.getText();
        return s;
    }

    public double getBalanceText (){
        String s = balanceText.getText();
        double q = Double.parseDouble(s);
        return q;
    }
    public void addUserButtonListener(ActionListener e) {
        addUserButton.addActionListener(e);
        System.out.println("Am apasat pe butonul de adaugare user");
    }



    //userDeleteCombo
    public void createUserDeleteComboBox()
    {
        userDeleteCombo.removeAllItems();
      //  for(String item : us.getAllUsersEmail()) //"szabycsillag@gmail.com"
        //           userDeleteCombo.addItem(item);
        for(String item : us.getAllUsersIDServ()) //"szabycsillag@gmail.com"
             userDeleteCombo.addItem(item);
    }

    public User getSelectDELETEComboBox() {
        String id = (String)userDeleteCombo.getSelectedItem();
        User userDeleted =  us.getUserbyId(id);
        System.out.println("Am gasit user ul dupa id: " + userDeleted);
        return userDeleted;
    }
    //userCreateAccountText

    public void userCreateAccountComboBox()
    {
        userCreateAccountText.removeAllItems();
        //  for(String item : us.getAllUsersEmail()) //"szabycsillag@gmail.com"
        //           userDeleteCombo.addItem(item);
        for(String item : us.getAllUsersIDServ()) //"szabycsillag@gmail.com"
            userCreateAccountText.addItem(item);
    }

    public User getuserCreateAccountSelected() {
        String id = (String)userCreateAccountText.getSelectedItem();
        User userDeleted =  us.getUserbyId(id);
        System.out.println("Am gasit user ul dupa id: " + userDeleted);
        return userDeleted;
    }

    //accountTypeText
    public String getAccountTypeSelected() {
        String type = (String)accountTypeText.getSelectedItem();
        return type;
    }

    //jComboBox1
    public void CreateComboBox1()
    {
        jComboBox1.removeAllItems();
        for(String item : us.getAllUsersIDServ()) //"szabycsillag@gmail.com"
            jComboBox1.addItem(item);
    }

    public User getUserComboBox1Selected() {
        String id = (String)jComboBox1.getSelectedItem();
        User userDeleted =  us.getUserbyId(id);
        System.out.println("Am gasit user ul dupa id: " + userDeleted);
        return userDeleted;
    }
    //jComboBox2
    //////////////////////////////////////////////////////////////////////////////

    public void CreateComboBox2(String userID)
    {
        jComboBox2.removeAllItems();
        us.getUserbyId(userID);
        for(String item : us.getUserIDBankAccount(userID)) //"szabycsillag@gmail.com"
            jComboBox2.addItem(item);
    }


////////////////////////////////////////////////////////////////////////////////
    public BankAccount getAccountComboBox2Selected() {
        String id = (String)jComboBox2.getSelectedItem();
        BankAccount acc=  us.getAccountfromId(id);
        System.out.println("Am gasit contul ul dupa id: " + acc);
        return acc;
    }







    public void CreateComboBox3()
    {
        jComboBox3.removeAllItems();
        for(String item : us.getAllUsersIDServ()) //"szabycsillag@gmail.com"
            jComboBox3.addItem(item);
    }

    public User getUserComboBox3Selected() {
        String id = (String)jComboBox3.getSelectedItem();
        User userDeleted =  us.getUserbyId(id);
        System.out.println("Am gasit user ul dupa id: " + userDeleted);
        return userDeleted;
    }
    //jComboBox2
    //////////////////////////////////////////////////////////////////////////////

    public void CreateComboBox4(String userID)
    {
        jComboBox4.removeAllItems();
        us.getUserbyId(userID);
        for(String item : us.getUserIDBankAccount(userID)) //"szabycsillag@gmail.com"
            jComboBox4.addItem(item);
    }


    ////////////////////////////////////////////////////////////////////////////////
    public BankAccount getAccountComboBox4Selected() {
        String id = (String)jComboBox4.getSelectedItem();
        BankAccount acc=  us.getAccountfromId(id);
        System.out.println("Am gasit contul ul dupa id: " + acc);
        return acc;
    }





    //addAccountButton
    public void addAccountButtonListener(ActionListener e) {
        addAccountButton.addActionListener(e);
        System.out.println("Am apasat pe butonul de adaugare cont");
    }

    //userDeleteButton
    public void deleteUserButtonListener(ActionListener e) {
        userDeleteButton.addActionListener(e);
        System.out.println("Am apasat pe butonul de stergere user");
    }

    //jButton1
    public void Button1Listener(ActionListener e) {
        jButton1.addActionListener(e);
        System.out.println("Am apasat pe butonul de stergere cont");
    }

    public void Button2Listener(ActionListener e) {
        jButton2.addActionListener(e);
        System.out.println("Am apasat pe butonul de creare credit");
    }
}
